channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - r-base==4.3.1
  - cairo
  - libpng
  - pkg-config
  - pandoc
  - r-dt=0.33
  - bioconductor-methylkit=1.28.0
  - r-plotly=4.10.4
  - r-ggplot2=3.5.1
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-readr=2.1.5
  - r-rmarkdown=2.28
  - r-rmdformats=1.0.4
  - r-pheatmap=1.0.12
  - r-viridis=0.6.5

